### ISSUE TITLE
An unhandled error has occurred inside Forge:

### ISSUE THREAD

**Issue by hienvuong2810** [spaceagetv/electron-bytenode-example#8]
When I clone project and install package with Yarn, after that start
```
✖ Launch Dev Servers

An unhandled error has occurred inside Forge:
Invalid options object. Dev Middleware has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'historyApiFallback'. These properties are valid:
   object { mimeTypes?, writeToDisk?, methods?, headers?, publicPath?, stats?, serverSideRender?, outputFileSysValidationError: Invalid options object. Dev Middleware has been initialized using an options object that does 
not match the API schema.
 - options has an unknown property 'historyApiFallback'. These properties are valid:
   object { mimeTypes?, writeToDisk?, methods?, headers?, publicPath?, stats?, serverSideRender?, outputFileSystem?, index? }
    at validate (E:\electron-bytenode-example\node_modules\schema-utils\dist\validate.js:104:11)
    at wdm (E:\electron-bytenode-example\node_modules\webpack-dev-middleware\dist\index.js:31:29)
    at E:\electron-bytenode-example\node_modules\@electron-forge\plugin-webpack\src\WebpackPlugin.ts:292:22    
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

any way to fix it?

**Comment by jjeff** [comment]
I haven't tested with yarn. Do you get an error with npm?
